(* sample mli showing everything that 'with fields' introduces *)

(*
  NOTES:
    (1) this file was hand generated and can therefore get out of sync with
        the actual interface of the generated code.
    (2) The file generated_test.mli does not have this problem as it is
        generated by ocamlp4o from the file test.mli
    (3) The types we list here are actually more general than those in
        generated_test.mli (see make_creator, for example)
*)


open Fieldslib
open Printf
open StdLabels

type ('a,'b) t = {
  dir : 'a * 'b;
  quantity : ('a , 'b) t;
  price : int * 'a;
  mutable cancelled : bool;
(*   symbol : string;   *)
} with fields
